import { chromium } from 'playwright-core'
const [src, out, w] = process.argv.slice(2)
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const p = await b.newPage({ viewport: { width: Number(w) || 1900, height: 1200 }, deviceScaleFactor: 2 })
await p.goto('file://' + src, { waitUntil: 'networkidle' })
await p.waitForTimeout(400)
const el = await p.$('.wrap')
await (el ?? p).screenshot({ path: out })
console.log(out)
await b.close()
